services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      SERVICES: iam,sts,s3,secretsmanager,lambda
      DEBUG: "0"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
